# Generated by Django 3.2.25 on 2026-05-08 19:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Имя')),
                ('color', models.CharField(choices=[('Gray', 'Серый'), ('Black', 'Чёрный'), ('White', 'Белый'), ('Ginger', 'Рыжий'), ('Mixed', 'Смешанный')], max_length=16, verbose_name='Цвет')),
                ('birth_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1986), django.core.validators.MaxValueValidator(2026)], verbose_name='Год рождения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Котик',
                'verbose_name_plural': 'Котики',
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название вакцины')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('validity_period', models.PositiveIntegerField(default=365, help_text='Через сколько дней после вакцинации нужна ревакцинация', verbose_name='Срок действия (дней)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Вакцина',
                'verbose_name_plural': 'Вакцины',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_date', models.DateField(verbose_name='Дата вакцинации')),
                ('next_due_date', models.DateField(help_text='Рассчитывается автоматически', verbose_name='Дата следующей вакцинации')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='cats.cat', verbose_name='Котик')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='cats.vaccine', verbose_name='Вакцина')),
            ],
            options={
                'verbose_name': 'Вакцинация',
                'verbose_name_plural': 'Вакцинации',
                'ordering': ['-vaccination_date'],
                'unique_together': {('cat', 'vaccine', 'vaccination_date')},
            },
        ),
        migrations.AddConstraint(
            model_name='cat',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_name_owner'),
        ),
    ]
